### ISSUE TITLE
Fails to start

### ISSUE THREAD

**Issue by roshanconnor123** [toddrob99/searcharr#10]
Hi
I am trying t run without docker
When I run the command `python3 searcharr.py`
It shows the following error

```
  File "<fstring>", line 1
    (r=)
      ^
SyntaxError: invalid syntax
```
Python3 Version : Python 3.6.9
Ubuntu 18

Please fix this
Thank you

**Comment by toddrob99** [comment]
Please upgrade to Python 3.8, as Python 3.6.9 does not support the f-string notation used within this application. For reference, see: https://docs.python.org/3/whatsnew/3.8.html#f-strings-support-for-self-documenting-expressions-and-debugging and https://tirkarthi.github.io/programming/2019/05/08/f-string-debugging.html.

**Comment by roshanconnor123** [comment]
> Please upgrade to Python 3.8, as Python 3.6.9 does not support the f-string notation used within this application. For reference, see: https://docs.python.org/3/whatsnew/3.8.html#f-strings-support-for-self-documenting-expressions-and-debugging and https://tirkarthi.github.io/programming/2019/05/08/f-string-debugging.html.

Thank you so much
I had both versions of python installed
But 3.6.9 was the default
Changed it and that fixed the problem
Good day to you
