### ISSUE TITLE
Unspecified error encountered while adding movie! [Same for Sonarr]

### ISSUE THREAD

**Issue by xavierxross** [toddrob99/searcharr#13]
Screen-Recording-> https://files.catbox.moe/gbvqum.mp4

**Comment by toddrob99** [comment]
That could be caused by a number of issues. Please check the log file for errors.

**Comment by xavierxross** [comment]
Here's the log btw- https://nekobin.com/jofixokuhi
I've enable the auth in sonarr/radarr


Sir can u create a telegram support pleech.

**Comment by toddrob99** [comment]
It looks like your quality profile is invalid. Go to `http://127.0.0.1:7878/api/profile?apikey=*****` (and same endpoint for Sonarr, replacing the port and API Key) to find the id of the profile you want to use. Or make sure you've copy/pasted the profile name exactly, because `HD 1080p 720p 4k 2160p Remux BDMV` is not matching when Searcharr tries to look up the id (from the API endpoint above). 

```
2020-12-22 15:23:17,069 -    ERROR - searcharr(7716):76 - Sonarr quality profile provided in settings [HD 1080p 720p 4k 2160p Remux BDMV] is invalid!
2020-12-22 15:23:17,141 -    ERROR - searcharr(7716):97 - Radarr quality profile provided in settings [HD 1080p 720p 4k 2160p Remux BDMV] is invalid!
```

If you are unable to resolve the issue, please enable debug logging by adding the `-v` command line argument when you run Searcharr, and provide a new log.

**Comment by xavierxross** [comment]
Searcharr is not opening now

Traceback (most recent call last):
  File "C:\****\Program Files\Searcharr\searcharr-1.4\searcharr.py", line 21, in <module>
    import settings
  File "C:\"**\Program Files\Searcharr\searcharr-1.4\settings.py", line 28
    radarr_quality_profile_id = "HDTV Bluray-1080p Bluray-1080p Bluray-2160p WEBDL-720p WEBDL-1080p WEBDL-2160p WEBRip-720p WEBRip-1080p WEBRip-2160p Remux-1080p Remux-2160p Raw-HD BR-DISK DVD""  # can be name or id value
                                                                                                                                                                                                                             ^
SyntaxError: EOL while scanning string literal

**Comment by toddrob99** [comment]
There are two double quotes on the end of the line. Make sure there are only two double quotes on the line (and no line breaks). It might be easier to put the id value of your quality profile rather than the name.

**Comment by xavierxross** [comment]
No I removed the double-quotation then also bot can lt send my req.  WEIRD!

**Comment by xavierxross** [comment]
log- https://nekobin.com/debekexoce

**Comment by xavierxross** [comment]
btw cant u make the bot to choose the video quality. its not like that we want 1080p for every movie/series

**Comment by toddrob99** [comment]
You still have invalid quality profile names in your config file for both Sonarr and Radarr. Again, you might want to try using the id from the API response I suggested before.

I will consider adding an option to allow the user to select a quality profile, but that is not something all users want (I want to force my users to add all movies using the same quality profile).

**Comment by xavierxross** [comment]
so I'll get  1 quality only ?

**Comment by xavierxross** [comment]
btw why dont u make a telegram support grp

**Comment by xavierxross** [comment]
And is it possible to req. "Any" or multiple quality rather than only 1

**Comment by toddrob99** [comment]
As stated before, I have noted your request to allow the user to select a quality profile when adding a series/movie, but that functionality is not currently supported. At this time, Searcharr requires a single quality profile name/id to be configured for each of Sonarr and Radarr, and all series/movies added through Searcharr will be added with the configured quality profile. 

I will also consider creating a Telegram support group.

Did you get Searcharr working after correcting the quality profile name/id in your settings?

**Comment by toddrob99** [comment]
I created a telegram group https://t.me/searcharr

**Comment by xavierxross** [comment]
> As stated before, I have noted your request to allow the user to select a quality profile when adding a series/movie, but that functionality is not currently supported. At this time, Searcharr requires a single quality profile name/id to be configured for each of Sonarr and Radarr, and all series/movies added through Searcharr will be added with the configured quality profile.
> 
> I will also consider creating a Telegram support group.
> 
> Did you get Searcharr working after correcting the quality profile name/id in your settings?

Yeah, Thenks a Lot

**Comment by xavierxross** [comment]
> I created a telegram group https://t.me/searcharr

Awesome!!
