### ISSUE TITLE
Ask user to select a tag when adding a series or movie

### ISSUE THREAD

**Issue by toddrob99** [toddrob99/searcharr#19]
Telegram user @JoaoPSVieira would like users to be presented with a list of tags that exist in Sonarr/Radarr when adding a series/movie, and asked to select one to add. This tag would be used to apply restrictions within indexer config.

**Comment by ocgineer** [comment]
I would like to see this as well, if this is something that is still planned, as I use certain tags to download only from certain submitters as a quick add on the current season. In addition, the added series cannot be marked as 'anime' and are just added as 'standard', not sure yet how this impacts the indexers.

**Comment by toddrob99** [comment]
Considering for v2

**Comment by toddrob99** [comment]
This will be included in v2, and will be in the 2.0-b5 build later tonight. Latest beta build is available in the `beta` branch of this repository, and through docker with the `toddrob/searcharr:beta` tag. See [draft release notes](https://github.com/toddrob99/searcharr/wiki/Draft-Release-Notes---v2.0) for more details.
