### ISSUE TITLE
Allow user to select a limited number of TV episodes to download when adding series to Sonarr

### ISSUE THREAD

**Issue by jsn0327** [toddrob99/searcharr#23]
I rarely want to download all available episodes for a series until I watch a few episodes to determine whether or not I like the show; especially for those shows with multiple seasons.  I would really like the option to choose the number of episodes to download initially, when adding the series.  I can then go back into Sonarr and mark the rest for download after I watch the first few.  An example would be, "Download the first 3 episodes of the first Season", "Download the entire first season", or "Download all available episodes."  It may be easier to list all available seasons when adding a show and allow the user to select which seasons and episodes that they want to download before adding the show to Sonarr.  

Because of the way that the bot is currently programmed for TV shows, I can only use it for Radarr.  The first TV show that I attempted to add tried to download all 5 seasons immediately.  Thanks for the awesome work!

**Comment by toddrob99** [comment]
I can potentially add an option to present the user with the options that Sonarr presents when adding a series, which off the top of my head are something like first season, latest season, all seasons. However, I don’t have time to do that in the short term. 

I suggest configuring searcharr to not add series as monitored, and then you can go into Sonarr and monitor just the first season or few episodes as you wish.

**Comment by jsn0327** [comment]
Thanks, that option at least makes the bot usable for adding TV Shows in the meantime.  Please let us know once you've added this feature.  Thanks.

**Comment by toddrob99** [comment]
The solution I mentioned before will be included in v2, and it will be available in v2.0-b4 tonight (docker tag: toddrob/searcharr:beta, beta branch if running from source).

**Comment by jsn0327** [comment]
> The solution I mentioned before will be included in v2, and it will be available in v2.0-b4 tonight (docker tag: toddrob/searcharr:beta, beta branch if running from source).

That’s great news, thanks for working on that! 

Do you think that it’s possible to add onto that feature and allow users to choose how many episodes of the chosen season to download? Like download the first 3 episodes of season 1.

**Comment by toddrob99** [comment]
The Sonarr API does not appear to support that level of granularity. It only goes to the season level when adding a series (just like when adding a series directly in Sonarr).

**Comment by jsn0327** [comment]
Does the API allow for monitoring/unmonitoring of episodes?

**Comment by toddrob99** [comment]
It looks like individual episodes can be managed through the [episode endpoint](https://github.com/Sonarr/Sonarr/wiki/Episode). What you are asking for would be pretty far beyond the scope of Searcharr, which is a tool for users to add series/movies to Sonarr/Radarr through Telegram. Choosing from the same options provided by Sonarr when adding a series (first/last/all season(s)) makes sense, but I am not interested in getting into episode-level management.

**Comment by jsn0327** [comment]
Fair enough. Thanks!
