### ISSUE TITLE
Configure Commands

### ISSUE THREAD

**Issue by echefel** [toddrob99/searcharr#25]
I would love it if we could configure the commands to be our own
such as replacing /series with /tv
/movies with /mv

Cheers!

**Comment by toddrob99** [comment]
Considering for v2

**Comment by toddrob99** [comment]
This will be in v2, and is already included in the beta branch & docker image (toddrob/searcharr:beta). 

Add the following to `settings.py` and modify as desired:

sonarr_series_command_aliases = ["series"]  # e.g. ["series", "tv", "t"]
radarr_movie_command_aliases = ["movie"]  # e.g. ["movie", "mv", "m"]

You can remove "series" and "movie" from the lists if you don't want those to be valid commands.
