### ISSUE TITLE
Add compatibility with readarr

### ISSUE THREAD

**Issue by phampyk** [toddrob99/searcharr#30]
I've got those 2 apps running alongside sonarr and radarr and it would be great to be able to use searcharr with them. As far as I'm aware they are based on radarr, if that helps. Lidarr is for music and readarr for books/audiobooks.

Thank you so much.

**Comment by ArnoldDeRuiter** [comment]
That would be simply lovely. :+1:

**Comment by toddrob99** [comment]
Will keep this request for readarr and #44 for lidarr

**Comment by aymanbagabas** [comment]
I stumbled on [pyarr](https://github.com/totaldebug/pyarr) lately and figured it might be helpful since it supports sonarr, radarr, readarr, and lidarr.

**Comment by toddrob99** [comment]
Thanks @aymanbagabas. So far I've just built a very lightweight wrapper that does exactly what Searcharr needs for each app. I'll keep pyarr in mind in case the need arises for something more robust.

**Comment by toddrob99** [comment]
> If anyone is interested in testing Searcharr+Readarr, check out https://github.com/aymanbagabas/searcharr/tree/readarr. There's also a Docker image https://hub.docker.com/r/aymanbagabas/searcharr

Thank you for the contribution. I am hoping to find time to review and test later this week.
