### ISSUE TITLE
no root folders enabled for Radarr

### ISSUE THREAD

**Issue by desatur8** [toddrob99/searcharr#32]
First of all, thanks @toddrob99 for a awesome piece of software, last week this time, actually Friday this time! i didnt know this existed nor have i ever really played with docker, since Friday evening till now, i have a proxmox server, running 4 LXC's with sonarr, radarr, transmission, searcharr and anout 10 other selfhosted app's .. its been overwhelming, but oh so much fun!

I have installed radarr, sonarr and searcharr. I started with sonarr, and everything works perfectly. Can search a /series, it picks it up, adds it, asks which of the root folders i have in sonarr it should donwload it to, it downloads, moves, updates, awesome!

Then i started with radarr, not so good! each time i search for a movie, searcharr picks it up, but on adding it says **_Error adding movie: no root folders enabled for Radarr! Please check your Searcharr configuration and try again_**

settings.py (which i will add in the end here) does in fact not have a root folder inserted, but neither does sonarr, because I am planning on having two folders for radarr, one for adult movies, uhm wait, that doesnt sound right! one for normal movies and one for kids movies, so i dont want a default path, i want it to ask.

Similarly sonarr doesnt have a default  path either and works perfectly

Lastly, i have rechecked my folders, permissions and even manually added a movie to radarr, it sees it, picks it up, throws it to transmission, and after completing the DL, radar picks it up again, renames and moves it, so im sure everything (paths and permissions) are a ok there.

Again! thanks alot for the app dude

EDIT: I just tried it with adding radarr_movie_paths = [1], and it works! but would love to keep it empty in order for me to choose /movies or /animated in telegram
```
"""
Searcharr
Sonarr & Radarr Telegram Bot
By Todd Roberts
https://github.com/toddrob99/searcharr
"""

# Searcharr Bot
searcharr_password = "REDACTED"  # Used to authenticate as a regular user to add series/movies
searcharr_admin_password = "REDACTED"  # Used to authenticate as admin to manage users

# Telegram
tgram_token = "REDACTED"

# Sonarr
sonarr_enabled = True
sonarr_url = "http://10.1.1.103:8989/"  # http://192.168.0.100:8989
sonarr_api_key = "REDACTED"
sonarr_quality_profile_id = ["SDTV"]  # can be name or id value - include multiple to allow the user to choose
sonarr_add_monitored = True
sonarr_search_on_add = True
sonarr_tag_with_username = True
sonarr_forced_tags = []  # e.g. ["searcharr", "friends-and-family"] - leave empty for none
sonarr_allow_user_to_select_tags = True
sonarr_user_selectable_tags = []  # e.g. ["custom-tag-1", "custom-tag-2"] - leave empty to let user choose from all tag>
sonarr_series_command_aliases = ["series"]  # e.g. ["series", "tv", "t"]`
sonarr_series_paths = []  # e.g. ["/tv", "/anime"] - can be full path or id value - leave empty to enable all
sonarr_season_monitor_prompt = False  # False - always monitor all seasons; True - prompt user to select from All, Firs>

# Radarr
radarr_enabled =  True
radarr_url = "http://10.1.1.103:7878"  # http://192.168.0.100:7878
radarr_api_key = "REDACTED"
radarr_quality_profile_id = ["HD - 720p/1080p"]  # can be name or id value - include multiple to allow the user to choo>radarr_add_monitored = True
radarr_search_on_add = True
radarr_tag_with_username = True
radarr_forced_tags = []  # e.g. ["searcharr", "friends-and-family"] - leave empty for none
radarr_allow_user_to_select_tags = True
radarr_user_selectable_tags = []  # e.g. ["custom-tag-1", "custom-tag-2"] - leave empty to let user choose from all tag>radarr_min_availability = "released"  # options: "announced", "inCinemas", "released"
radarr_movie_command_aliases = ["movie"]  # e.g. ["movie", "mv", "m"]
radarr_movie_paths = []  # e.g. ["/movies", "/other-movies"] - can be full path or id value - leave empty to enable all 
```

**Comment by toddrob99** [comment]
Can you change your setting back to `radarr_movie_paths = []` and post your log? You should have an entry that starts like this:

`No valid Radarr root folder(s) provided! Using all of the root folders I found in Radarr: `

It may also be helpful to post the output from the root folder endpoint: `http://10.1.1.103:7878/api/v3/RootFolder?apikey=YOUR_RADARR_API_KEY`

**Comment by toddrob99** [comment]
Also, if you haven't already, please [enable debug logging](https://github.com/toddrob99/searcharr/wiki/Enable-Debug-Logging).

**Comment by desatur8** [comment]
ok cool, will do! will enable logging and post debug in the next day

thanks

**Comment by desatur8** [comment]
I am quite new to this whole thing, so just trying to figure out how to enable logging from within portainer, changed the CMD from 'python3' 'searcharr.py' to 'python3' 'searcharr.py -v' but got a error and 'python3' 'searcharr.py' '-v' does give a output in the logs but something in the lines of no log line matching the '' filter

For the second one though, this is the output of ``http://10.1.1.103:7878/api/v3/RootFolder?apikey=YOUR_RADARR_API_KEY``

```
[
  {
    "path": "/movies/Radarr_2022",
    "accessible": true,
    "freeSpace": 9900359680,
    "unmappedFolders": [],
    "id": 2
  }
]
```

**Comment by toddrob99** [comment]
I think you might be looking at the console log, which is disabled by default. Try `'python3' 'searcharr.py' '-cv'` to enable console and verbose/debug logging. The logs should be written to a file too, in the logs folder. If you have a path mapped for `/app/logs` in your docker container, you can view the log files in there.

The API response confirms you only have one root folder mapped, so your configuration of `radarr_movie_paths = []` should result in the user NOT being prompted to select it. You can also try `radarr_movie_paths = [2]` since the id for your root folder is `2` according to the API response.

**Comment by desatur8** [comment]
> I think you might be looking at the console log, which is disabled by default. Try `'python3' 'searcharr.py' '-cv'` to enable console and verbose/debug logging. The logs should be written to a file too, in the logs folder. If you have a path mapped for `/app/logs` in your docker container, you can view the log files in there.
> 
> The API response confirms you only have one root folder mapped, so your configuration of `radarr_movie_paths = []` should result in the user NOT being prompted to select it. You can also try `radarr_movie_paths = [2]` since the id for your root folder is `2` according to the API response.

Hey @toddrob99 , sorry to make this your problem, as I know this isnt part of your support scope, but how do I browse the docker container? with other containers deployed, i would do a ``docker exec -t -i mycontainer /bin/bash`` and it will drop into the console, with searcharr however i get a ``OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "/bin/bash": stat /bin/bash: no such file or directory: unknown`` error, which seems it can't connect to /bin/bash?

**Comment by desatur8** [comment]
@toddrob99 yes, currently, I only have one root folder configured with searcharr. but it didnt auto select it. I tested it with putting in ``radarr_movie_paths = [2]`` and it worked, no error and movie was picked up by radarr. I change it back to ``radarr_movie_paths = []`` now to test for you and submit the logs, and ... it worked again. No error. I am not sure if maybe i did something wrong the first time, or of the change from [2] to [] triggered and fixed something.

but as we stand now, it seems the issue was sorted, can i mark this as closed? 

Thanks for the amazing app, and the awesome support!

**Comment by toddrob99** [comment]
I usually do `docker exec -it searcharr sh`.

Glad it's working. Without seeing the logs, I have no idea why it wasn't working before.
