### ISSUE TITLE
No module named 'telegram' on startup

### ISSUE THREAD

**Issue by Bigmikko** [toddrob99/searcharr#40]
Hey, I followed the setup instructions but I can't figure this one out, what have I missed, I get the following when I try to start searcharr (ran it from source):
sudo python3.8 searcharr.py
Traceback (most recent call last):
  File "searcharr.py", line 16, in <module>
    from telegram import InlineKeyboardButton, InlineKeyboardMarkup, InputMediaPhoto
ModuleNotFoundError: No module named 'telegram'

**Comment by toddrob99** [comment]
Try this first:

`python3.8 -m pip install -r requirements.txt`

**Comment by Bigmikko** [comment]
Ah, ofc, thank you! It works perfectly now!
