### ISSUE TITLE
[Payment Request] Crypto

### ISSUE THREAD

**Issue by Pantar2205** [toddrob99/searcharr#45]
Please consider a method to donate to the project via Bitcoin etc
Thank you for your work.

**Comment by toddrob99** [comment]
I will look into a good way to add crypto as an option for donations. In the meantime, if you would like to donate via crypto, you can use any of the following addresses (others available if desired). Be sure to send only the listed asset type to each address!

Bitcoin (BTC): 3P92LR9wgy1r13WwxqhGJL7UUdtA1THxZk
Ethereum (ETH): 0x2CC76dDCC9fD7e89687740d6b0D7235A0f8eaA2E
Shiba Inu (SHIB): 0x6557c990e55d87C6b35093f7fd1167323930e66f
Dogecoin (DOGE): DGMxaFU7nv6hfQ4974Ep1eLXag5LKvmnFm
USD Coin (USDC): 0x0d4826D4D4F8d65F9A2e58E2CD32b70b8DAC59F5

Thank you for the support!

**Comment by toddrob99** [comment]
Added the addresses to a wiki page for now: https://github.com/toddrob99/searcharr/wiki/Donations-via-Cryptocurrency
