### ISSUE TITLE
Support language profile selection for Sonarr

### ISSUE THREAD

**Issue by LucaVignati** [toddrob99/searcharr#46]
Please consider letting the user choose the language for the series. Radarr includes the language in the quality profile but Sonarr has a different parameter called "Language profile" which from my understanding is not currently selectable via Searcharr. Thank you for your work, this is an amazing tool!

**Comment by toddrob99** [comment]
I didn't even know language profiles existed in sonarr... I will look into adding support for them.

**Comment by LucaVignati** [comment]
Thanks!

**Comment by toddrob99** [comment]
@LucaVignati, it appears Sonarr is deprecating language profiles and adding language support to custom quality profiles instead. After upgrading to Sonarr v4 in my test instance, the response to the languageprofile API endpoint has changed to this:

```json
[
  {
    "name": "Deprecated",
    "upgradeAllowed": true,
    "cutoff": {
      "id": 1,
      "name": "English"
    },
    "languages": [
      {
        "language": {
          "id": 1,
          "name": "English"
        },
        "allowed": true
      }
    ],
    "id": 1
  }
]
```

As a result, I am going to remove language profile support from Searcharr v3.
