### ISSUE TITLE
Connection Issues

### ISSUE THREAD

**Issue by LordZeuss** [toddrob99/searcharr#47]
I recently had issues, everything was working perfectly, until recently I replaced my router with a new one, and now my searcharr bot is having network issues. I have not changed anything in the docker or docker-compose.yml files, and so I am not sure why I am having this issue. I even have the same static IP set for the device that runs it as I did before. Any help would be greatly appreciated. I'll post the pastebin link of the downloaded log file from docker

Thanks!
 (here is the downloaded log file as well)

**Comment by toddrob99** [comment]
I'm afraid there is not much I can do to help with this... I have no idea why your docker container is having connection issues with api.telegram.org, but according to the logs, it is.

Also, your Telegram bot token is exposed in the logs you posted. You should change it.
