### ISSUE TITLE
[support] wiki page on how to add docker image in truenas SCALE

### ISSUE THREAD

**Issue by whomade** [toddrob99/searcharr#50]
Is there a way a more experienced person can help with a writeup? As noobs struggle with getting the configuration correct

**Comment by toddrob99** [comment]
I don't have truenas or any knowledge of how it differs from a standard docker setup. If anyone else wants to contribute to documentation, I would be happy to add to the wiki.

**Comment by whomade** [comment]
I’ll keep bumbling around and if I figure something out I’ll post here

**Comment by famewolf** [comment]
> Is there a way a more experienced person can help with a writeup? As noobs struggle with getting the configuration correct

Important parts shown.  Basically you need to setup some directories for it to store data.  Mine are on a dataset on a mirrored ssd which makes things faster. [and good deeds do have rewards as while pasting these I realized my /apps/logs internal mount had a typo to "/appps/logs" so fix that part.]  The settings.py file is a copy of the https://github.com/toddrob99/searcharr/blob/main/settings-sample.py edited to match my sonarr, radarr etc.  You'll need a telegram bot obviously...a google on "botfather" will probably find tutorials on how to set one up.

![2023-06-05_23-42](https://github.com/toddrob99/searcharr/assets/4558832/ef5eedb6-0bc4-4a96-b832-d92287433661)
![2023-06-05_23-43](https://github.com/toddrob99/searcharr/assets/4558832/4dfd64dc-6628-422e-b46d-322352788fc8)
![2023-06-05_23-43_1](https://github.com/toddrob99/searcharr/assets/4558832/6738bd54-7b4a-4427-9ac0-97d3f5f04a68)

**Comment by toddrob99** [comment]
https://github.com/toddrob99/searcharr/wiki/Setup-on-TrueNAS-using-docker

Thank you
