### ISSUE TITLE
change language

### ISSUE THREAD

**Issue by hugolino** [toddrob99/searcharr#55]
hi, i don't know what i'm doing wrong, 
I clone the git repository, i added a logs directory, edit my settings.py, my docker-compose.yml and add a fr-fr.yml file in the lang folder.
In my setting.py i put "fr-fr".

When i compose my container the log says : 
`2022-09-14 20:54:49,514 -    ERROR - searcharr(548159638600):1749 - Error loading lang/fr-fr.yml. Confirm searcharr_language in settings.py has a corresponding yml file in the lang subdirectory. Using default (English) language file.`

What i'm doing wrong ?

Thanks for the bot by the way !

**Comment by toddrob99** [comment]
The docker image does not include `lang\fr-fr.yml` yet. Even though you have it in your local folder, it's not included in the docker image unless you build a new docker image from your local repo that includes the additional file.

You can mount the file in your docker container until I am able to test and publish with the French language file included (should be fairly soon, maybe this weekend). In your docker-compose.yml, add a volume mapping similar to the one for `settings.py`, similar to this: `- ./fr-fr.yml:/app/lang/fr-fr.yml`. Put fr-fr.yml in the same folder as docker-compose.yml and that should work, or adjust the path accordingly.

**Comment by toddrob99** [comment]
I was able to find some time to complete adding French support and publish v2.2. It should be available on docker hub shortly.

**Comment by hugolino** [comment]
thank you very much !
