### ISSUE TITLE
Caught error: Wrong type of the web page content

### ISSUE THREAD

**Issue by frazzyfin** [toddrob99/searcharr#6]
When searching for `/movie black panther`, there is no response. This error appears in the log:

`ERROR - searcharr(139873103756064):705 - Caught error: Wrong type of the web page content`

**Comment by toddrob99** [comment]
The poster for Black Panther is http://image.tmdb.org/t/p/original/uxzzxijgPIY7slzFvMotPv8wjKA.jpg, which is a valid image. For some reason, Telegram rejects the image. I was unable to find any documentation to explain what Telegram doesn't like about the image, or how to make it work. In lieu of a real solution, I am adding logic to retry with a default poster when the error happens. Fix included in v1.3.5, docker images will be updated in 30 minutes.
