### ISSUE TITLE
Sonarr V4 support

### ISSUE THREAD

**Issue by RemuxKid** [toddrob99/searcharr#63]
Seems I'm getting a 404 error on one of the Sonarr v4 endpoints

```
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://127.0.0.1:8989/sonarr/api/profile?apikey=REDACTED
```

Assuming there'd be other changes to the API as well, thats the only error I'm getting so far though.

**Comment by RemuxKid** [comment]
Looks like v2 of the API is deprecated in V4. Looks like it may need to be upgraded to the v3 API.

**Comment by toddrob99** [comment]
I will include support for api v3 and backward compatibility in v3 by the end of next week
