### ISSUE TITLE
Series Season

### ISSUE THREAD

**Issue by halfloaf123** [toddrob99/searcharr#66]
Add feature to request for a specific season for TV Series, like the big bang theory season 10 or season 5 etc

**Comment by toddrob99** [comment]
The ability to select First, Latest, or All season(s) was added in v2.0. Use the setting `sonarr_season_monitor_prompt=True` to enable.

From v2.0 release notes: 
Add option to prompt user to monitor first, latest, or all season(s) when adding a series to Sonarr (add sonarr_season_monitor_prompt=True to settings.py; default is False, same as prior functionality, monitor all seasons) (https://github.com/toddrob99/searcharr/issues/23)
