### ISSUE TITLE
Running on Ubuntu, fails to start

### ISSUE THREAD

**Issue by gr4z** [toddrob99/searcharr#7]
Sorry for the dumb question, I am trying to follow your instructions and I don't use Docker but trying to start using **python searcharr.py** and get the error:
`  File "<fstring>", line 1
    (r=)
      ^
`
?

**Comment by gr4z** [comment]
Solved by using Docker!

**Comment by toddrob99** [comment]
That error meant your version of python was too old to support f-strings. You would have to run at least python 3.6. The Docker image uses python 3.9.
