### ISSUE TITLE
Feature to request different quality if another quality is already added.

### ISSUE THREAD

**Issue by leonard4546** [toddrob99/searcharr#73]
Currently we can add any 1 quality through bot. and we cant add same title again as the bot says "Already Added".

is it possible to add this feature. this will be very useful specially for readarr. as some users want Audiobook and some want Ebook.

same applies for TV/Movies

**Comment by toddrob99** [comment]
Searcharr supports multiple quality profiles for each of the *arr apps, but a single profile has to be selected for each title. The *arr apps only support adding a given title one time. Many people maintain two copies of Radarr, one for HD and one for 4K. You could do the same with Readarr, one for eBook and one for Audiobook.

**Comment by leonard4546** [comment]
so I will have to deploy two different bots?

**Comment by toddrob99** [comment]
Yes, searcharr currently supports one instance of each *arr app. You will need a second instance of searcharr if you wish to use it for a second instance of the *arr app(s). 

You can simplify the process of using two bots if you add them to a group and configure non-overlapping commands for the two bots. For example set the book command to /ebook for one bot and /audiobook for the other. That way only one bot will respond to each command and you/your users don't need to switch between bots themselves.
