### ISSUE TITLE
[Discussion] Searcharr can't find a tv show but it does exists through one of the indexsers

### ISSUE THREAD

**Issue by msarsha** [toddrob99/searcharr#76]
How is the search done? looks like its not using the indexers to suggest the available movies \ shows

**Comment by toddrob99** [comment]
Searcharr does the search through Sonarr (Radarr, Readarr). It will present the same results as if you did a search in Sonarr itself. I think Sonarr uses thetvdb, so any series that exists there will be included in the search results. Once a series is added to Sonarr, Sonarr will search your indexers to see if it can obtain the monitored episodes. That is the whole point of Sonarr.
