### ISSUE TITLE
Trying to run from Raspberry Pi

### ISSUE THREAD

**Issue by alejakun** [toddrob99/searcharr#77]
Hi,

I'm running the latest release from a raspberry-pi, however the logs say:

```
searcharr       | Traceback (most recent call last):
searcharr       |   File "/app/searcharr.py", line 25, in <module>
searcharr       |     import settings
searcharr       | ModuleNotFoundError: No module named 'settings'
```

When the architecture is not supported it usually sends a very different error, which makes me think this should work (I validated and the base container you're using supports RBP architecture). So, I'm a little lost. Hope you can help me.

Best regards.

**Comment by toddrob99** [comment]
As the error says, your settings.py file is missing. It should be in the same folder as searcharr.py, either physically in that folder or mapped to /app/settings.py if you're using docker. 

You can save a copy of [settings-sample.py](https://raw.githubusercontent.com/toddrob99/searcharr/main/settings-sample.py) as settings.py and modify as appropriate. See [wiki](https://github.com/toddrob99/searcharr/wiki/Configuration-::-settings.py) for detailed descriptions of the settings.

**Comment by alejakun** [comment]
Sorry, failed to report back, had a problem with the volume mounts but it's working now, thanks!
