### ISSUE TITLE
can't get several command_aliases to work

### ISSUE THREAD

**Issue by hhenne1** [toddrob99/searcharr#79]
Hi,
i love your bot, but i'm having an issue setting it up.
no matter what i do or try, i cant get sonarr_series_command_aliases and readarr_book_command_aliases to work with several values.
as soon as i put several values for sonarr, the docker container (toddrob/searcharr:latest) just loops with a python error.
setting several values for radarr works fine.
and setting any value for readarr_book_command_aliases never works, not even with a single one, and reverts to its default.

2023-05-16 18:58:50,731 -     INFO - searcharr(139795833956160):66 - Searcharr v3.2.1 - Logging started!
2023-05-16 18:58:51,895 -  WARNING - searcharr(139795833956160):362 - No readarr_book_command_aliases setting found. Please add readarr_book_command_aliases to settings.py (e.g. readarr_book_command_aliases=["book", "bk"]. Defaulting to ["book"].

i attached the settings.py with the lines i tried.

[settings.py.txt](https://github.com/toddrob99/searcharr/files/11490340/settings.py.txt)

maybe someone has a hint what i'm doing wrong?

**Comment by hhenne1** [comment]
wops.. had an alias with a space in sonarr_series_command_aliases .. that fixed the reboot-loop.. 
readarr_book_command_aliases still does not get recognized though..

**Comment by hhenne1** [comment]
sorry that i keep adding notes to this, but.. if i just use readarr_book_command_aliases, it does not get recognized and defaults to book, but runs.
if i replace it with readarr_movie_command_aliases, the app crashes and bootloops.
but if i use both, it works just the way i hoped it would.

the configuration-help (https://github.com/toddrob99/searcharr/wiki/Configuration-::-settings.py) states under readarr_book_command_aliases -> Example: readarr_movie_command_aliases = ["book", "b"]

thats why i thought it would be worth a shot..
so, i got it working now, though it looks quite weird in the config.
thanks :*

**Comment by toddrob99** [comment]
Thanks for posting. There is actually a bug in the searcharr code that it's looking for `readarr_movie_command_aliases` instead of `readarr_book_command_aliases`, and if the `movie` version isn't in the settings file, it will set the `book` version (the actual setting) to the default value. I'm sure this was a copy/paste mistake. I will be fixing this in v3.2.2 shortly. I also corrected the wiki.

https://github.com/toddrob99/searcharr/blame/main/searcharr.py#L360
