### ISSUE TITLE
MDBList ratings support

### ISSUE THREAD

**Issue by rkl92** [toddrob99/searcharr#83]
Hello, first, thank you for this wonderful tool, it's so useful.
Second, I would like to ask if it's possible to implement support for MDBList api, I don't ask for full support, but for ratings, MDBList offers the best range of ratings across the board for movies. So, when searching for a movie, also show up the ratings in the telegram message, with our MDBList api key used in the config. Don't know if this is something people would want, but I would love it.

Thanks for this tool once again.

**Comment by toddrob99** [comment]
Thanks for the suggestion. At this time, Searcharr is not intended to be used for discovery, so I don't think I will implement this enhancement. Searcharr is intended to be used to find a specific show/movie/book and add it, and there are many other tools that can be used for discovery before adding via Searcharr. If you are not tied to Telegram, I would suggest Overseer--it is great for discovery and adding in one tool.
