### ISSUE TITLE
Search by IMDb, TVDB, or other scraper ID

### ISSUE THREAD

**Issue by RemuxKid** [toddrob99/searcharr#9]
Sometimes it's difficult to find the exact movie you're looking for, would it be possible to search by ID?

**Comment by toddrob99** [comment]
You can search by TVDB (series) or TMDB (movies) by prefixing the id with the db (lower case). Not all movies will return results based on IMDB id, but that does work sometimes too. Series search does not seem to support IMDB id. 

For example: `/movie tmdb:1542` will return Office Space, but `/movie imdb:tt0151804` won't even though the IMDB id is in the search results for that movie. Other movies don't have IMDB ids listed. An example of a movie that can be looked up by IMDB id is Frozen II: `/movie imdb:tt4520988`. That is my experience using Radarr v2. 

The same will work for series using TVDB id: `/series tvdb:82066`, but attempting to search by IMDB id will return `IMDb's What's on TV (2019)` regardless of ID searched. That is my experience using Sonarr v3.
