### ISSUE TITLE
Support for Sonarr v4

### ISSUE THREAD

**Issue by alejakun** [toddrob99/searcharr#93]
Since this month, the latest stable version of sonarr is v4, however the bot seems to be unable to handle it:

searcharr       |   File "/app/sonarr.py", line 26, in __init__
searcharr       |     if not self.sonarr_version.startswith("4."):
searcharr       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searcharr       | AttributeError: 'NoneType' object has no attribute 'startswith'

Best regards!

**Comment by jordanella** [comment]
I am using 4.0.1.929 without issue.

It appears to be failing to return a version during the discover_version function call. I imagine if you check your debug log you'll see a message saying so.

Does your Sonarr installation use a different port? I'd verify that your sonarr_url is set correctly in your configuration settings.

**Comment by toddrob99** [comment]
@alejakun try restarting Searcharr so it will re-discover your Sonarr version.
