### ISSUE TITLE
string index out of range

### ISSUE THREAD

**Issue by cvandingelen** [toddrob99/searcharr#96]
Hi.
Love searcharr, it worked for me before. Now, I had to switch to  a new server. Since I was starting over, I also created a new bot. I made the settings.py file and it seems to be correct.

When starting the container though, I get:

`Traceback (most recent call last):
  File "/app/searcharr.py", line 2118, in <module>
    tgr = Searcharr(settings.tgram_token)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/searcharr.py", line 264, in __init__
    readarr.Readarr(
  File "/app/readarr.py", line 18, in __init__
    if api_url[-1] == "/":
       ~~~~~~~^^^^
IndexError: string index out of range`

In the logs, there is only a warning that no valid root folders have been provided and that it therefore will use all the folders.
Hope you can help me out.

**Comment by toddrob99** [comment]
It is throwing an error on your Readarr api url setting. Do you have Readarr enabled but no api url defined?

**Comment by cvandingelen** [comment]
I don't use readarr, should I leave this part out of the file then?

**Comment by toddrob99** [comment]
Check the sample settings file in this repo because it seems like you were used to an older version of the app. Add/update `readarr_enabled = False` to your settings file to disable Readarr support.

**Comment by cvandingelen** [comment]
Ok, that worked. Thanks
